version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/valint main.go

    run:
        desc: Run the app
        cmds:
          - GOFLAGS=-mod=mod go run main.go
 
    clean:
        desc: Remove the output.go file
        cmds:
        - rm output.go